import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      // appearance={{
      //   layout: {
      //     socialButtonsVariant: "iconButton",
      //     logoImageUrl: "/icons/poom-logo.png",
      //   },
      //   variables: {
      //     colorText: "#fff",
      //     colorPrimary: "#0E78F9",
      //     colorBackground: "#1C1F2E",
      //     colorInputBackground: "#252A41",
      //     colorInputText: "#fff",
      //   },
      // }}
      >
        <body className={`${inter.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
